// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCowBlyq16O7MQoUnIZlB3txoBzcJiC62Y',
    appId: '1:72223686325:web:25585f330ea9140dc148fc',
    messagingSenderId: '72223686325',
    projectId: 'rofs-blood-connect',
    authDomain: 'rofs-blood-connect.firebaseapp.com',
    storageBucket: 'rofs-blood-connect.appspot.com',
    measurementId: 'G-GMYHNB5YWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_qbCv1kCcY-aIu-T89CJISfmi7PTctvo',
    appId: '1:72223686325:android:ad8c9b0a38181f99c148fc',
    messagingSenderId: '72223686325',
    projectId: 'rofs-blood-connect',
    storageBucket: 'rofs-blood-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz69L-MKFnGrjT2P_rjPGiTZy9h3piA_Q',
    appId: '1:72223686325:ios:7cd41ec25389f402c148fc',
    messagingSenderId: '72223686325',
    projectId: 'rofs-blood-connect',
    storageBucket: 'rofs-blood-connect.appspot.com',
    iosBundleId: 'com.example.rbc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz69L-MKFnGrjT2P_rjPGiTZy9h3piA_Q',
    appId: '1:72223686325:ios:7cd41ec25389f402c148fc',
    messagingSenderId: '72223686325',
    projectId: 'rofs-blood-connect',
    storageBucket: 'rofs-blood-connect.appspot.com',
    iosBundleId: 'com.example.rbc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCowBlyq16O7MQoUnIZlB3txoBzcJiC62Y',
    appId: '1:72223686325:web:3b45bbc3ed81a510c148fc',
    messagingSenderId: '72223686325',
    projectId: 'rofs-blood-connect',
    authDomain: 'rofs-blood-connect.firebaseapp.com',
    storageBucket: 'rofs-blood-connect.appspot.com',
    measurementId: 'G-94843TNZV8',
  );
}